#!/usr/bin/env python
import os 
import subprocess
import socket

internal_ntp = "server"
external_ntp = "hora.rediris.es"
gva_ntp = "ntp.gva.es"

ntp_server=external_ntp

try:
	socket.gethostbyname(internal_ntp)
	ntp_server=internal_ntp
except:
	pass


try:
	socket.gethostbyname(gva_ntp)
	ntp_server=gva_ntp
except:
	pass


print "[lliurex-ntpdate] Setting date via %s"%ntp_server
os.system("ntpdate -s %s"%(ntp_server))
os.system("hwclock --systohc")
 
